# passed in by env vars (TF_VAR)
variable "GCP_PROJECT_ID" {}
variable "GCP_REGION" {}
variable "GCP_DATASET_NAME" {}
variable "GCP_DATASET_TABLE_NAME" {}
variable "COMPUTE_ENGINE_NAME" {}
variable "COMPUTE_ENGINE_MACHINE_TYPE" {}
variable "COMPUTE_ENGINE_REGION" {}
variable "LOCAL_SERVICE_ACCOUNT_FILE_PATH" {}
variable "REMOTE_SERVICE_ACCOUNT_FILE_PATH" {}
variable "SERVICE_ACCOUNT_EMAIL" {}
variable "DBT_PROFILE_NAME" {}
variable "PREFECT_AGENT_QUEUE" {}
variable "PREFECT_GCP_CREDENTIALS_BLOCK_NAME" {}
variable "PREFECT_DBT_CORE_BLOCK_NAME" {}
variable "PREFECT_GITHUB_BLOCK_NAME" {}
variable "GITHUB_REPO_URL" {}
