name: Trigger Agent VM Rebuild

env:
  PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
  PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
  PREFECT_AGENT_QUEUE_NAME: ${{ secrets.PREFECT_AGENT_QUEUE_NAME }}
  GCP_RESOURCE_REGION: ${{ secrets.GCP_RESOURCE_REGION }}
  GCP_CREDENTIALS_JSON: $${{ secrets.GCP_CREDENTIALS_JSON }}

on:
  workflow_dispatch:

jobs:
  build-and-apply-deployment:
    name: Provision Prefect Agent VM

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.GCP_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: "${{ env.GCP_RESOURCE_REGION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ env.GCP_CREDENTIALS_JSON }}
